
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'DIV MAIS MENOS MUL NUMexp1 : exp1 MAIS exp2\n             | exp1 MENOS exp2\n             | exp2\n    exp2 : exp2 DIV exp3\n             | exp2 MUL exp3\n             | exp3\n    exp3 : NUM\n    '
    
_lr_action_items = {'NUM':([0,5,6,7,8,],[4,4,4,4,4,]),'$end':([1,2,3,4,9,10,11,12,],[0,-3,-6,-7,-1,-2,-4,-5,]),'MAIS':([1,2,3,4,9,10,11,12,],[5,-3,-6,-7,-1,-2,-4,-5,]),'MENOS':([1,2,3,4,9,10,11,12,],[6,-3,-6,-7,-1,-2,-4,-5,]),'DIV':([2,3,4,9,10,11,12,],[7,-6,-7,7,7,-4,-5,]),'MUL':([2,3,4,9,10,11,12,],[8,-6,-7,8,8,-4,-5,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'exp1':([0,],[1,]),'exp2':([0,5,6,],[2,9,10,]),'exp3':([0,5,6,7,8,],[3,3,3,11,12,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> exp1","S'",1,None,None,None),
  ('exp1 -> exp1 MAIS exp2','exp1',3,'p_exp_1','sintatico.py',6),
  ('exp1 -> exp1 MENOS exp2','exp1',3,'p_exp_1','sintatico.py',7),
  ('exp1 -> exp2','exp1',1,'p_exp_1','sintatico.py',8),
  ('exp2 -> exp2 DIV exp3','exp2',3,'p_exp_2','sintatico.py',13),
  ('exp2 -> exp2 MUL exp3','exp2',3,'p_exp_2','sintatico.py',14),
  ('exp2 -> exp3','exp2',1,'p_exp_2','sintatico.py',15),
  ('exp3 -> NUM','exp3',1,'p_exp_3','sintatico.py',20),
]
